### ISSUE TITLE
Routes with extension

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic-routing#27]
A **very** common endpoint is to do some sort of a match on an extension:

```
/foo/bar.jpg
```

Usually, you want to get `bar` as a variable value. I propose a new route segment type: `ext` that would allow make it super simple to setup these types of routes.

There are three general scenarios:

1. Match _any_ extension
2. Match a single extension
3. Match one of a specific set of extensions

I think something like the following should work:

```
/foo/<file:ext>
/foo/<file:ext:jpg>
/foo/<file:ext:jpg|png|gif|svg>
```

This would result in two passed variables: whatever is defined, and the extension as ext.

For example:

```python
@app.get("/invoice/<invoice_id:ext:pdf|txt>")
async def invoice_handler(request, invoice_id, ext):
    ...
```

**Comment by jacebrowning** [comment]
How would one specify the type of the file stem?

e.g. To ensure that `invoice_id` is a UUID and the extension is `pdf` or `text`.

**Comment by ahopkins** [comment]
> How would one specify the type of the file stem?
> 
> e.g. To ensure that `invoice_id` is a UUID and the extension is `pdf` or `text`.

:thinking: Hmm.... that is not something I considered. This implementation would accept anything for the filename.

**Comment by jacebrowning** [comment]
Perhaps something like this?

```
@app.get("/invoice/<invoice_id:uuid.ext:pdf|txt>")
async def invoice_handler(request, invoice_id, ext):
    ...
```

Using `.` as the separator could support all of these patterns:

```
/foo/<file.ext> # type is assumed to be 'file:str'
/foo/<file.ext:jpg>
/foo/<file.ext:jpg|png|gif|svg>
/foo/<file:uuid.ext>
/foo/<file:path.ext:jpg>
/foo/<file:int.ext:jpg|png|gif|svg>
```

---

Alternatively, if the `file` in `<file:ext:png>` also matched paths (`/` character) then that would be sufficient for [my use case](https://github.com/jacebrowning/memegen/blob/ef9fa6c14310fdedc3d9ce1857c4ad6036085559/app/views/memes.py#L195).

**Comment by ahopkins** [comment]
I have been looking at this one some more so we can finally wrap it up. The real challenge for me has been to determine what is the appropriate syntax here. While I can appreciate what @jacebrowning offered with `file.ext`, it really breaks a lot of other patterns and the entire concept that `ext` is itself the parameter "type".

Therefore, I offer this as the syntax:

```
/foo/<file:ext> # type is assumed to be 'file:str'
/foo/<file:ext=jpg>
/foo/<file:ext=jpg|png|gif|svg>
/foo/<file=uuid:ext>
/foo/<file=path:ext=jpg>
/foo/<file=int:ext=jpg|png|gif|svg>
```
