### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by nicoddemus** [sanic-org/sanic-routing#33]
Hi,

I'm adding `sanic-routing` to conda-forge in order to get `sanic` to build again:

https://github.com/conda-forge/sanic-feedstock/pull/34

However neither the repository nor the package contain a `LICENSE` file, which is kind of a soft-requirement to build packages on conda-forge.

It would be great to add it to the repository and to the package in order to make the package on conda-forge more compliant. 👍 

https://github.com/conda-forge/staged-recipes/pull/14753

**Comment by ahopkins** [comment]
Good point. Was an oversight since it's a temporary repo. It will be gone in about a month or so and merged into the main repo. Until then I'll add a license.
