### ISSUE TITLE
Invalid declaration: <entity_id>:meta

### ISSUE THREAD

**Issue by hieulw** [sanic-org/sanic-routing#55]
I have this path `/<entity_id>:meta` in my route, and it works in the old version.
But now it doesn't work anymore due to this REGEX
https://github.com/sanic-org/sanic-routing/blob/main/sanic_routing/patterns.py#L22

It said that I'm using invalid pattern `/<entity_id>:meta`, but it was intended and not easily to change because it was used to retrieve metadata for frontend team. 

I hope you fix the regex pattern to suit more cases.
Thank you!

**Comment by hieulw** [comment]
I attempt to change the regex, but it will not recognize a route that contains colon `:`
How can I change this behavior ? `:` is really needed in my route, and It cannot change

**Comment by hieulw** [comment]
```python
@app.get(r"/<entity_id:([^/]+)\:meta>")
```
This approach works very well, but it seems `/<entity_id>` and `/<entity_id:([^/]+)\:meta>` are considered the same route, which not what I expected.

**Comment by ahopkins** [comment]
@hieulw Nothing we can't solve without a bit of regex magic :magic_wand: 

```python
@app.get(r"/<entity_id:([^/]+)\:mode>")
async def handler_mode(request: Request, entity_id):
    return json({"entity_id": entity_id, "mode": True})


@app.get(r"/<entity_id:(?P<entity_id>[^/]+)(?!\:mode)>")
async def handler_reg(request: Request, entity_id):
    return json({"entity_id": entity_id, "mode": False})
```

```
$ curl localhost:9999/1234 localhost:9999/4567:mode
{"entity_id":"1234","mode":false}
{"entity_id":"4567","mode":true}
```
