### ISSUE TITLE
Incorrect handling of `pattern` argument for `register_pattern`

### ISSUE THREAD

**Issue by ahankinson** [sanic-org/sanic-routing#56]
The type annotation on `register_pattern` gives `Pattern` as the acceptable type.

However, an exception is thrown if you do provide a pattern with `re.compile`, complaining that it must be a `str`. 

So:

```python
app.router.register_pattern(
    "nestr",
    nonempty_str,
    re.compile(r"^[^/]+$")
)
```

passes the type checker, but fails with an exception, while

```python
app.router.register_pattern(
    "nestr",
    nonempty_str,
    r"^[^/]+$"
)
```

does not raise an exception, but highlights the pattern argument as a mismatching type.

The relevant lines are:

https://github.com/sanic-org/sanic-routing/blob/main/sanic_routing/router.py#L241-L243

https://github.com/sanic-org/sanic-routing/blob/main/sanic_routing/router.py#L272-L276

**Comment by ahankinson** [comment]
I can make a PR, but would appreciate some direction: I can either make it raise on non-Pattern arguments, or change the function annotation to `str`.

**Comment by ahopkins** [comment]
Yeah, I noticed that today actually.

I think ideally we would accept both by annotation and at runtime. IIRC, the strings are compiled in that register method.

If you are up for the challenge, I'd love to see a PR to fix.
